// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0d30NHLLrg8rmGXmnagfDpYqoO_ftsM',
    appId: '1:675731155768:web:433296e6034425a5c66fcd',
    messagingSenderId: '675731155768',
    projectId: 'ecommerce-b0cd4',
    authDomain: 'ecommerce-b0cd4.firebaseapp.com',
    storageBucket: 'ecommerce-b0cd4.firebasestorage.app',
    measurementId: 'G-T7XRKHZZHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwMFkuiuFMHdS9f2FMznImlgw00LC8FxY',
    appId: '1:675731155768:android:e2fa6bf266f44aaec66fcd',
    messagingSenderId: '675731155768',
    projectId: 'ecommerce-b0cd4',
    storageBucket: 'ecommerce-b0cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiN5dE7Di7F51Je0v0NBYZPx2gDRyiwzE',
    appId: '1:675731155768:ios:de54780e88bb1803c66fcd',
    messagingSenderId: '675731155768',
    projectId: 'ecommerce-b0cd4',
    storageBucket: 'ecommerce-b0cd4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiN5dE7Di7F51Je0v0NBYZPx2gDRyiwzE',
    appId: '1:675731155768:ios:de54780e88bb1803c66fcd',
    messagingSenderId: '675731155768',
    projectId: 'ecommerce-b0cd4',
    storageBucket: 'ecommerce-b0cd4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu0d30NHLLrg8rmGXmnagfDpYqoO_ftsM',
    appId: '1:675731155768:web:e6502c955b0e1ab3c66fcd',
    messagingSenderId: '675731155768',
    projectId: 'ecommerce-b0cd4',
    authDomain: 'ecommerce-b0cd4.firebaseapp.com',
    storageBucket: 'ecommerce-b0cd4.firebasestorage.app',
    measurementId: 'G-EFG3DNFPFW',
  );
}
